server.port=8080
spring.application.name=cybercore-backend

# Spring AI Ollama Ayarları
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3
spring.ai.ollama.chat.options.temperature=0.7